// Letter layouts as data, one registry entry per layout. This is the
// only file to edit when adding or changing a layout: the dropdown,
// the validation, and the tests all read from LAYOUTS.
//
// An entry has a `label` (shown in the dropdown) and a `static`
// hand-written slot map. Slot map shape: sector (N/E/S/W) ->
// direction -> four letters by crossing count, index 0 = 1 crossing =
// innermost. null = empty slot (types nothing, draws nothing).
//
// The generated experiment layouts (qwerty-region, pure frequency)
// and the per-layout language switch were removed 2026-08-26: the end
// state is one combined en+cs layout, so every surviving layout is a
// static map. Git history keeps the build(language) machinery.

// Approximate letter frequency, most common first, base 26 Latin
// letters only. Hand-written from published tables, not
// corpus-derived; see the discussion in features.md. Used by
// tools/generate-qwerty8pen.mjs (frequency promotion); cs is kept for
// the future combined en+cs layout optimization.
export const FREQUENCY = {
  en: ['e','t','a','o','i','n','s','h','r','d','l','c','u','m','w','f','g','y','p','b','v','k','j','x','q','z'],
  cs: ['o','e','a','n','t','s','i','v','l','d','k','r','u','p','m','c','h','z','y','j','b','g','f','w','x','q'],
};

export const LAYOUTS = {
  'original-8pen': {
    label: 'Original 8pen',
    // Transcribed from 8pen.png (repo root), a screenshot of the
    // original app. The geometry now matches the original directly:
    // X-shaped arms, sectors up/right/down/left. Reading order per
    // line: innermost glyph first (1 crossing). All 26 letters plus 6
    // punctuation marks fill the 32 slots exactly; the frequent ones
    // (. and ,) sit innermost, the rare ones (' ? ! @) outermost.
    static: {
      N: { CW: ['i', 'd', 'g', 'z'], CCW: ['y', 'x', 'k', "'"] },
      E: { CW: ['o', 'u', 'w', '!'], CCW: ['a', 'r', 'f', '?'] },
      S: { CW: ['e', 'l', 'p', 'q'], CCW: ['t', 'h', 'b', '@'] },
      W: { CW: ['.', 's', 'c', 'v'], CCW: [',', 'n', 'm', 'j'] },
    },
  },

  'qwerty-8pen': {
    label: 'QWERTY 8pen',
    // Letters only: punctuation is deliberately absent because it will
    // get its own gesture mechanism later. Rings come from
    // original-8pen with frequency promotion into the freed slots
    // (n s to ring 1, c m to ring 2, v j to ring 3, English ranking),
    // so six common letters are cheaper than in the original and every
    // other letter keeps its crossing count. Within each ring, slots
    // go to the letters whose direction from the QWERTY keyboard
    // center best matches the slot's on-screen direction. Generated by
    // tools/generate-qwerty8pen.mjs; edit and re-run that script
    // instead of hand-editing this map. This entry stays pure script
    // output, the reproducible baseline for comparison; hand tuning
    // happens in urza-layout below. The six null slots in ring 4 are
    // reserved real estate and must stay empty.
    static: {
      N: { CW: ['y', 'u', 'p', null], CCW: ['t', 'r', 'w', null] },
      E: { CW: ['o', 'h', 'k', null], CCW: ['i', 'l', 'j', null] },
      S: { CW: ['a', 'c', 'v', null], CCW: ['n', 'm', 'b', null] },
      W: { CW: ['e', 'd', 'f', 'q'], CCW: ['s', 'x', 'g', 'z'] },
    },
  },

  'urza-layout': {
    label: 'urza',
    // The hand-owned layout: this map, right here, is the source of
    // truth. No script regenerates it. Edit it directly, and log
    // every change with its dated reasoning in layout-tuning.md.
    // Seeded 2026-08-26 from the qwerty-8pen generator output with
    // one change: a and s traded ring-1 slots so the word "is"
    // traces a figure eight.
    static: {
      N: { CW: ['y', 'u', 'p', null], CCW: ['t', 'r', 'w', null] },
      E: { CW: ['o', 'h', 'k', null], CCW: ['i', 'l', 'j', null] },
      S: { CW: ['s', 'c', 'v', null], CCW: ['n', 'm', 'b', null] },
      W: { CW: ['e', 'd', 'f', 'q'], CCW: ['a', 'x', 'g', 'z'] },
    },
  },

};

// What the page starts on when no saved choice exists (main.js
// remembers the dropdown in localStorage). The dropdown still lists
// everything.
export const DEFAULT_LAYOUT = 'urza-layout';

export function buildLayout(id) {
  const def = LAYOUTS[id];
  if (!def) throw new Error(`Unknown layout: ${id}`);
  return def.static;
}
