namespace Yap.Services;

public static class EmojiData
{
    public static readonly Dictionary<string, (string Icon, string[] Emojis)> Categories = new()
    {
        ["smileys"] = ("😀", new[]
        {
            "😀", "😃", "😄", "😁", "😆", "😅", "🤣", "😂", "🙂", "🙃", "🫠", "😉", "😊",
            "😇", "🥰", "😍", "🤩", "😘", "😗", "☺️", "😚", "😙", "🥲", "😌",
            "😋", "😛", "😜", "🤪", "😝", "🤑", "🤗", "🤭", "🫢", "🫣", "🤫", "🤔", "🫡",
            "🤐", "🤨", "😐", "😑", "😶", "🫥", "😶‍🌫️", "😏", "😒", "🙄", "😬", "🤥",
            "🫨", "🙂‍↔️", "🙂‍↕️", "😮‍💨", "😔", "😪", "🤤", "😴", "💤", "🫩", "😷", "🤒", "🤕", "🤢",
            "🤮", "🤧", "🥴", "😵", "😵‍💫", "🤯", "🫪", "🤠", "🥳", "🥸", "😎", "🤓", "🧐",
            "😕", "🫤", "😟", "🙁", "☹️", "😮", "😯", "😲", "😳", "🥺", "🥹",
            "😦", "😧", "😨", "😰", "😥", "😢", "😭", "😱", "😖", "😣", "😞", "😓",
            "😩", "😫", "🥱", "😤", "😡", "😠", "🤬", "🥵", "🥶", "😈", "👿", "💀", "☠️",
            "💩", "🤡", "👹", "👺", "👻", "🧟", "👽", "👾", "🤖", "🎃",
            "😺", "😸", "😹", "😻", "😼", "😽", "🙀", "😿", "😾"
        }),
        ["gestures"] = ("👋", new[]
        {
            "🤝", "🫶", "🤲", "👐", "🙌", "👏", "👍", "👎", "👊", "✊", "🤛",
            "🤜", "🫷", "🫸", "🤞", "✌️", "🫰", "🤟", "🤘", "👌", "🤌", "🤏",
            "🫳", "🫴", "👈", "👉", "👆", "👇", "☝️", "✋", "🤚", "🖐️", "🖖",
            "👋", "🤙", "🫲", "🫱", "💪", "🦾", "🖕", "✍️", "🙏", "🫵", "👀",
            "🤦", "🤷", "🙅", "🙆", "🙋", "💁", "🙇", "🤦‍♂️", "🤦‍♀️", "🤷‍♂️", "🤷‍♀️",
            "💅", "🤳", "🦿", "🦵", "🦶", "👂", "🦻", "👃", "🧠", "👁️", "👅", "👄", "💋",
            "❤️", "🧡", "💛", "💚", "💙", "💜", "🖤", "🤍", "🤎", "💔", "❤️‍🔥", "💕",
            "💞", "💓", "💗", "💖", "💘", "💝", "💟"
        }),
        ["animals"] = ("🐶", new[]
        {
            "🐶", "🐱", "🐈", "🐈‍⬛", "🐭", "🐹", "🐰", "🦊", "🐻", "🐼", "🐻‍❄️", "🐨", "🐯", "🦁",
            "🐮", "🐷", "🐸", "🐵", "🙈", "🙉", "🙊", "🐒", "🐔", "🐧", "🐦", "🐤",
            "🐣", "🐥", "🦆", "🦅", "🦉", "🦇", "🐺", "🐗", "🐴", "🦄", "🐝", "🪱",
            "🐛", "🦋", "🐌", "🐞", "🐜", "🪰", "🪲", "🪳", "🦟", "🦗", "🕷️", "🦂",
            "🐢", "🐍", "🦎", "🦖", "🦕", "🐙", "🦑", "🦐", "🦞", "🦀", "🐡", "🐠",
            "🐟", "🐬", "🐳", "🐋", "\U0001FACD", "🦈", "🐊", "🐅", "🐆", "🦓", "🦍", "🦧", "🐘"
        }),
        ["nature"] = ("🌿", new[]
        {
            "🌸", "💐", "🌹", "🥀", "🌺", "🌻", "🌼", "🌷", "🌱", "🪴", "🌲", "🌳",
            "🌴", "🌵", "🍀", "☘️", "🍁", "🍂", "🍃", "🌾", "🍄", "🌿",
            "☀️", "🌤️", "⛅", "🌥️", "🌦️", "🌧️", "⛈️", "🌩️", "🌨️", "❄️", "☃️", "⛄",
            "🌪️", "🌫️", "🌊", "💧", "💦", "💨", "🌈", "☁️", "⚡", "💥", "☄️", "⭐", "🌟", "✨",
            "🌑", "🌒", "🌓", "🌔", "🌕", "🌖", "🌗", "🌘", "🌙", "🌚", "🌛", "🌜", "🌝", "🌞"
        }),
        ["food"] = ("🍔", new[]
        {
            "🍏", "🍎", "🍐", "🍊", "🍋", "🍌", "🍉", "🍇", "🍓", "🫐", "🍈", "🍒",
            "🍑", "🥭", "🍍", "🥥", "🥝", "🍅", "🍆", "🥑", "🥦", "🥬", "🥒", "🌶️",
            "🫑", "🌽", "🥕", "🫒", "🧄", "🧅", "🥔", "🍠", "🥐", "🥯", "🍞", "🥖",
            "🥨", "🧀", "🥚", "🍳", "🧈", "🥞", "🧇", "🥓", "🥩", "🍗", "🍖", "🦴",
            "🌭", "🍔", "🍟", "🍕", "🫓", "🥪", "🥙", "🧆", "🌮", "🌯", "🫔", "🥗",
            "🥘", "🫕", "🍝", "🍜", "🍲", "🍛", "🍣", "🍱", "🥟", "🦪", "🍤", "🍙",
            "🍚", "🍘", "🍥", "🥠", "🥮", "🍢", "🍡", "🍧", "🍨", "🍦", "🥧", "🧁",
            "🍰", "🎂", "🍮", "🍭", "🍬", "🍫", "🍿", "🍩", "🍪", "🌰", "🥜", "🍯",
            "☕", "🍵", "🧃", "🥛", "🍼", "🫖", "🧋", "🍶", "🍺", "🍻", "🥂", "🍷"
        }),
        ["activities"] = ("⚽", new[]
        {
            "⚽", "🏀", "🏈", "⚾", "🥎", "🎾", "🏐", "🏉", "🥏", "🎱", "🪀", "🏓",
            "🏸", "🏒", "🏑", "🥍", "🏏", "🪃", "🥅", "⛳", "🪁", "🏹", "🎣", "🤿",
            "🥊", "🥋", "🎽", "🛹", "🛼", "🛷", "⛸️", "🥌", "🎿", "⛷️", "🏂", "🪂",
            "🏋️", "🏋️‍♂️", "🏋️‍♀️", "🤼", "🤸", "🤺", "⛹️", "🤾", "🏌️", "🏇", "🧘", "🏄", "🏊", "🤽",
            "🚣", "🧗", "🚵", "🚴", "🏃", "🏆", "🥇", "🥈", "🥉", "🏅", "🎖️", "🏵️", "🎗️",
            "🎫", "🎟️", "🎪", "🎭", "🎨", "🎬", "🎤", "🎧", "🎼", "🎵", "🎶", "🎹", "🥁", "🪘",
            "🎷", "🎺", "📯", "🪗", "🎸", "🪕", "🪉", "🎻", "🪈", "🪇", "🎲", "♟️", "🎯", "🎳", "🎮", "🎰"
        }),
        ["travel"] = ("🚗", new[]
        {
            "🚗", "🚕", "🚙", "🚌", "🚎", "🏎️", "🚓", "🚑", "🚒", "🚐", "🛻", "🚚",
            "🚛", "🚜", "🏍️", "🛵", "🚲", "🛴", "🛺", "🚨", "🚔", "🚍", "🚘", "🚖",
            "🚡", "🚠", "🚟", "🚃", "🚋", "🚞", "🚝", "🚄", "🚅", "🚈", "🚂", "🚆",
            "🚇", "🚊", "🚉", "✈️", "🛫", "🛬", "🛩️", "💺", "🛰️", "🚀", "🛸", "🚁",
            "🛶", "⛵", "🚤", "🛥️", "🛳️", "⛴️", "🚢", "⚓", "🪝", "⛽", "🚧", "🚦",
            "🚥", "🗿", "🗽", "🗼", "🏰", "🏯", "🏟️", "🎡", "🎢", "🎠", "⛲", "⛱️",
            "🏖️", "🏝️", "🏜️", "🌋", "⛰️", "🏔️", "🗻", "🏕️", "🛖", "🏠", "🏡", "🏘️"
        }),
        ["objects"] = ("💡", new[]
        {
            "⌚", "📱", "💻", "⌨️", "🖥️", "🖨️", "🖱️", "🖲️", "💽", "💾", "💿", "📀",
            "📼", "📷", "📸", "📹", "🎥", "📽️", "🎞️", "📞", "☎️", "📟", "📠", "📺",
            "📻", "🎙️", "🎚️", "🎛️", "🧭", "⏱️", "⏲️", "⏰", "🕰️", "⌛", "⏳", "📡",
            "🔋", "🪫", "🔌", "💡", "🔦", "🕯️", "🪔", "🔥", "🧯", "🛢️", "💸", "💵", "💴", "💶",
            "💷", "🪙", "💰", "💳", "💎", "⚖️", "🪜", "🧰", "🪛", "🔧", "🔨", "⚒️",
            "🛠️", "⛏️", "🪚", "🔩", "⚙️", "🪤", "🧱", "⛓️", "🧲", "🔫", "💣", "🧨",
            "🪓", "🔪", "🗡️", "⚔️", "🛡️", "🚬", "⚰️", "🪦", "⚱️", "🏺", "🔮", "📿",
            "🔑", "🗝️", "🔒", "🔓", "📦", "✉️", "📝", "📖", "📚", "📉", "🔔", "🔕", "📢", "📣",
            "🎁", "🎀", "🎈", "🎉", "🎊", "✏️", "✂️", "📎", "🧸", "🚪", "🛏️", "🛋️",
            "🚿", "🛁", "🪞", "🪑", "🧩"
        }),
        ["symbols"] = ("❤️", new[]
        {
            "❤️", "🧡", "💛", "💚", "💙", "💜", "🖤", "🤍", "🤎", "💔", "❣️", "💕",
            "💞", "💓", "💗", "💖", "💘", "💝", "💟", "☮️", "✝️", "☪️", "🕉️", "☸️",
            "✡️", "🔯", "🕎", "☯️", "☦️", "🛐", "⛎", "♈", "♉", "♊", "♋", "♌",
            "♍", "♎", "♏", "♐", "♑", "♒", "♓", "🆔", "⚛️", "🉑", "☢️", "☣️",
            "📴", "📳", "🈶", "🈚", "🈸", "🈺", "🈷️", "✴️", "🆚", "💮", "🉐", "㊙️",
            "㊗️", "🈴", "🈵", "🈹", "🈲", "🅰️", "🅱️", "🆎", "🆑", "🅾️", "🆘", "❌",
            "⭕", "🛑", "⛔", "📛", "🚫", "💯", "💢", "♨️", "🚷", "🚯", "🚳", "🚱",
            "🔞", "📵", "🚭", "❗", "❓", "‼️", "⁉️", "🔅", "🔆", "〽️", "⚠️", "🚸",
            "🔱", "⚜️", "🔰", "♻️", "✅", "🈯", "💹", "❇️", "✳️", "❎", "🌐", "💠"
        }),
        ["flags"] = ("🏳️", new[]
        {
            "🏳️", "🏴", "🏁", "🚩", "🏳️‍🌈", "🏳️‍⚧️", "🏴‍☠️", "🇺🇸", "🇬🇧", "🇨🇦", "🇦🇺", "🇩🇪",
            "🇫🇷", "🇮🇹", "🇪🇸", "🇯🇵", "🇰🇷", "🇨🇳", "🇷🇺", "🇧🇷", "🇲🇽", "🇮🇳", "🇳🇱", "🇧🇪",
            "🇨🇭", "🇦🇹", "🇸🇪", "🇳🇴", "🇩🇰", "🇫🇮", "🇵🇱", "🇺🇦", "🇬🇷", "🇹🇷", "🇮🇱", "🇸🇦",
            "🇮🇶", "🇦🇪", "🇪🇬", "🇿🇦", "🇳🇬", "🇰🇪", "🇦🇷", "🇨🇴", "🇨🇱", "🇵🇪", "🇻🇪", "🇵🇭", "🇮🇩",
            "🇹🇭", "🇻🇳", "🇲🇾", "🇸🇬", "🇳🇿", "🇮🇪", "🇵🇹", "🇨🇿", "🇭🇺", "🇷🇴", "🇧🇬"
        })
    };

    /// <summary>
    /// Searchable keywords for each emoji. Used by the emoji picker search.
    /// </summary>
    public static readonly Dictionary<string, string> EmojiKeywords = new()
    {
        // Smileys
        ["😀"] = "grinning face happy smile",
        ["😃"] = "grinning face big eyes happy smile",
        ["😄"] = "grinning face smiling eyes happy",
        ["😁"] = "beaming face smiling eyes grin",
        ["😆"] = "grinning squinting face laughing lol xd",
        ["😅"] = "grinning face sweat nervous",
        ["😂"] = "face tears joy laughing crying lol",
        ["🤣"] = "rolling floor laughing rofl lol",
        ["🙂"] = "slightly smiling face",
        ["🙃"] = "upside down face sarcasm silly ironic",
        ["🫠"] = "melting face melt dissolve disappear hot",
        ["😉"] = "winking face wink",
        ["😊"] = "smiling face smiling eyes blush happy",
        ["😇"] = "smiling face halo angel innocent",
        ["🥰"] = "smiling face hearts love adore",
        ["😍"] = "smiling face heart eyes love",
        ["🤩"] = "star struck excited starstruck amazing",
        ["😘"] = "face blowing kiss love",
        ["😗"] = "kissing face kiss",
        ["☺️"] = "smiling face relaxed warm happy",
        ["😚"] = "kissing face closed eyes",
        ["😙"] = "kissing face smiling eyes",
        ["🥲"] = "smiling face with tear happy sad bittersweet",
        ["😌"] = "relieved face calm peaceful",
        ["😋"] = "face savoring food yummy delicious tongue",
        ["😛"] = "face tongue stuck out",
        ["😜"] = "winking face tongue stuck out playful",
        ["🤪"] = "zany face crazy wild goofy",
        ["😝"] = "squinting face tongue stuck out",
        ["🤑"] = "money mouth face dollar rich",
        ["🤗"] = "hugging face hug open hands",
        ["🤭"] = "face hand over mouth giggle oops",
        ["🫢"] = "face open eyes hand over mouth surprised oops",
        ["🫣"] = "face peeking eye shy scared peek",
        ["🤫"] = "shushing face quiet secret hush",
        ["🤔"] = "thinking face hmm wonder ponder",
        ["🫡"] = "saluting face salute respect yes sir",
        ["🤐"] = "zipper mouth face shut silent",
        ["🤨"] = "face raised eyebrow skeptical suspicious",
        ["😐"] = "neutral face blank expressionless",
        ["😑"] = "expressionless face blank",
        ["😶"] = "face without mouth silent mute",
        ["🫥"] = "dotted line face invisible hidden depressed",
        ["😶‍🌫️"] = "face in clouds foggy spaced out dissociated",
        ["😏"] = "smirking face smug smirk",
        ["😒"] = "unamused face unhappy displeased",
        ["🙄"] = "face rolling eyes annoyed whatever",
        ["😬"] = "grimacing face awkward cringe nervous",
        ["🤥"] = "lying face pinocchio nose liar",
        ["🫨"] = "shaking face earthquake vibrate shock",
        ["🙂‍↔️"] = "head shaking horizontally no disagree",
        ["🙂‍↕️"] = "head shaking vertically yes nod agree",
        ["😮‍💨"] = "face exhaling sigh relief breath",
        ["😔"] = "pensive face sad thoughtful",
        ["😪"] = "sleepy face tired",
        ["🤤"] = "drooling face drool",
        ["😴"] = "sleeping face zzz sleep",
        ["💤"] = "zzz sleep sleeping snore tired bored",
        ["🫩"] = "face bags under eyes tired exhausted sleepy fatigue dark circles no sleep worn out",
        ["😷"] = "face medical mask sick",
        ["🤒"] = "face thermometer sick fever ill",
        ["🤕"] = "face head bandage hurt injured",
        ["🤢"] = "nauseated face sick green vomit",
        ["🤮"] = "face vomiting puke throw up sick",
        ["🤧"] = "sneezing face sneeze tissue sick cold",
        ["🥴"] = "woozy face drunk dizzy tipsy",
        ["😵"] = "face crossed out eyes dizzy dead",
        ["😵‍💫"] = "face spiral eyes dizzy hypnotized stunned",
        ["🤯"] = "exploding head mind blown shocked",
        ["🫪"] = "distorted face glitch warped wavy disoriented confused overwhelmed dizzy",
        ["🤠"] = "cowboy hat face western",
        ["🥳"] = "partying face party celebrate birthday",
        ["🥸"] = "disguised face nose glasses incognito",
        ["😎"] = "smiling face sunglasses cool",
        ["🤓"] = "nerd face glasses geek",
        ["🧐"] = "face monocle inspect curious",
        ["😕"] = "confused face puzzled",
        ["🫤"] = "face diagonal mouth unsure skeptical meh",
        ["😟"] = "worried face concern",
        ["🙁"] = "slightly frowning face sad",
        ["☹️"] = "frowning face sad unhappy",
        ["😮"] = "face open mouth surprised wow",
        ["😯"] = "hushed face surprised stunned",
        ["😲"] = "astonished face shocked amazed",
        ["😳"] = "flushed face embarrassed shy",
        ["🥺"] = "pleading face puppy eyes begging",
        ["🥹"] = "face holding back tears emotional touched",
        ["😦"] = "frowning face open mouth",
        ["😧"] = "anguished face distressed",
        ["😨"] = "fearful face scared afraid",
        ["😰"] = "anxious face sweat nervous worried",
        ["😥"] = "sad relieved face disappointed",
        ["😢"] = "crying face tear sad",
        ["😭"] = "loudly crying face sob bawling",
        ["😱"] = "face screaming fear horror",
        ["😖"] = "confounded face frustrated",
        ["😣"] = "persevering face struggle",
        ["😞"] = "disappointed face sad",
        ["😓"] = "downcast face sweat",
        ["😩"] = "weary face tired exhausted",
        ["😫"] = "tired face exhausted fed up",
        ["🥱"] = "yawning face sleepy bored tired",
        ["😤"] = "face steam nose angry triumph huffing",
        ["😡"] = "pouting face angry red mad",
        ["😠"] = "angry face mad",
        ["🤬"] = "face symbols mouth swearing cursing",
        ["🥵"] = "hot face sweating overheated heat",
        ["🥶"] = "cold face freezing frozen ice blue",
        ["😈"] = "smiling face horns devil evil",
        ["👿"] = "angry face horns devil imp",
        ["💀"] = "skull dead death skeleton",
        ["☠️"] = "skull crossbones death poison",
        ["💩"] = "pile poo poop shit",
        ["🤡"] = "clown face circus",
        ["👹"] = "ogre monster japanese oni",
        ["👺"] = "goblin monster japanese tengu",
        ["👻"] = "ghost halloween spooky boo",
        ["🧟"] = "zombie undead walking dead exhausted braindead",
        ["👽"] = "alien extraterrestrial ufo space",
        ["👾"] = "alien monster space invader game",
        ["🤖"] = "robot face bot machine",
        ["🎃"] = "jack-o-lantern pumpkin halloween",
        ["😺"] = "grinning cat face happy",
        ["😸"] = "grinning cat smiling eyes",
        ["😹"] = "cat tears joy laughing",
        ["😻"] = "smiling cat heart eyes love",
        ["😼"] = "cat wry smile smirk",
        ["😽"] = "kissing cat face",
        ["🙀"] = "weary cat face shocked",
        ["😿"] = "crying cat face sad",
        ["😾"] = "pouting cat face angry",

        // Gestures
        ["👋"] = "waving hand hello hi bye wave",
        ["🤚"] = "raised back hand stop",
        ["🖐️"] = "hand splayed fingers open",
        ["✋"] = "raised hand stop high five",
        ["🖖"] = "vulcan salute spock star trek",
        ["👌"] = "ok hand okay perfect",
        ["🤌"] = "pinched fingers italian gesture",
        ["🤏"] = "pinching hand small tiny little bit",
        ["✌️"] = "victory hand peace sign two",
        ["🤞"] = "crossed fingers luck hope",
        ["🤟"] = "love you gesture hand sign",
        ["🤘"] = "sign horns rock metal",
        ["🤙"] = "call me hand hang loose shaka",
        ["👈"] = "backhand index pointing left",
        ["👉"] = "backhand index pointing right",
        ["👆"] = "backhand index pointing up",
        ["🖕"] = "middle finger flip off",
        ["👇"] = "backhand index pointing down",
        ["☝️"] = "index pointing up one",
        ["👍"] = "thumbs up good yes like approve",
        ["👎"] = "thumbs down bad no dislike",
        ["✊"] = "raised fist solidarity power",
        ["👊"] = "oncoming fist bump punch",
        ["🤛"] = "left facing fist bump",
        ["🤜"] = "right facing fist bump",
        ["👏"] = "clapping hands applause clap bravo",
        ["🙌"] = "raising hands celebrate hooray",
        ["👐"] = "open hands jazz",
        ["🤲"] = "palms up together prayer receive",
        ["🤝"] = "handshake deal agreement",
        ["🫶"] = "heart hands love gesture care",
        ["🫷"] = "leftwards pushing hand stop push",
        ["🫸"] = "rightwards pushing hand stop push",
        ["🫰"] = "hand index finger thumb crossed money snap",
        ["🫳"] = "palm down hand drop lower dismiss",
        ["🫴"] = "palm up hand offer give receive",
        ["🫲"] = "leftwards hand left point",
        ["🫱"] = "rightwards hand right point",
        ["🫵"] = "index pointing at viewer you point",
        ["🙏"] = "folded hands pray please thank you namaste",
        ["🤦"] = "person facepalming facepalm smh disbelief exasperated ugh",
        ["🤦‍♂️"] = "man facepalming facepalm smh disbelief exasperated ugh",
        ["🤦‍♀️"] = "woman facepalming facepalm smh disbelief exasperated ugh",
        ["🤷"] = "person shrugging shrug idk dunno whatever meh",
        ["🤷‍♂️"] = "man shrugging shrug idk dunno whatever meh",
        ["🤷‍♀️"] = "woman shrugging shrug idk dunno whatever meh",
        ["🙅"] = "person gesturing no nope forbidden stop deny",
        ["🙆"] = "person gesturing ok yes fine agree",
        ["🙋"] = "person raising hand question volunteer me pick",
        ["💁"] = "person tipping hand sassy information sarcasm whatever",
        ["🙇"] = "person bowing sorry apology thank you respect dogeza",
        ["✍️"] = "writing hand pen",
        ["💅"] = "nail polish manicure beauty",
        ["🤳"] = "selfie phone camera",
        ["💪"] = "flexed biceps strong muscle arm",
        ["🦾"] = "mechanical arm prosthetic robot",
        ["🦿"] = "mechanical leg prosthetic robot",
        ["🦵"] = "leg kick limb",
        ["🦶"] = "foot kick stomp",
        ["👂"] = "ear hear listen",
        ["🦻"] = "ear hearing aid deaf",
        ["👃"] = "nose smell sniff",
        ["🧠"] = "brain smart think mind",
        ["👀"] = "eyes look see watch stare watching lurking nosy drama",
        ["👁️"] = "eye see look watch",
        ["👅"] = "tongue lick taste",
        ["👄"] = "mouth lips kiss",
        ["💋"] = "kiss mark lipstick smooch",
        ["❤️"] = "red heart love",
        ["🧡"] = "orange heart love",
        ["💛"] = "yellow heart love",
        ["💚"] = "green heart love",
        ["💙"] = "blue heart love",
        ["💜"] = "purple heart love",
        ["🖤"] = "black heart dark love",
        ["🤍"] = "white heart love pure",
        ["🤎"] = "brown heart love",
        ["💔"] = "broken heart heartbreak sad",
        ["❤️‍🔥"] = "heart fire passion burning love",
        ["💕"] = "two hearts love",
        ["💞"] = "revolving hearts love",
        ["💓"] = "beating heart love pulse",
        ["💗"] = "growing heart love",
        ["💖"] = "sparkling heart love shine",
        ["💘"] = "heart arrow cupid love",
        ["💝"] = "heart ribbon gift love",
        ["💟"] = "heart decoration love",

        // Animals
        ["🐶"] = "dog face puppy pet",
        ["🐱"] = "cat face kitten pet",
        ["🐈"] = "cat pet feline kitty",
        ["🐈‍⬛"] = "black cat pet feline kitty",
        ["🐭"] = "mouse face rat",
        ["🐹"] = "hamster face pet",
        ["🐰"] = "rabbit face bunny",
        ["🦊"] = "fox face",
        ["🐻"] = "bear face",
        ["🐼"] = "panda face",
        ["🐻‍❄️"] = "polar bear arctic white",
        ["🐨"] = "koala face australia",
        ["🐯"] = "tiger face",
        ["🦁"] = "lion face king",
        ["🐮"] = "cow face moo",
        ["🐷"] = "pig face oink",
        ["🐸"] = "frog face toad ribbit",
        ["🐵"] = "monkey face",
        ["🙈"] = "see no evil monkey blind",
        ["🙉"] = "hear no evil monkey deaf",
        ["🙊"] = "speak no evil monkey mute quiet",
        ["🐒"] = "monkey primate",
        ["🐔"] = "chicken hen rooster",
        ["🐧"] = "penguin bird arctic",
        ["🐦"] = "bird tweet",
        ["🐤"] = "baby chick bird",
        ["🐣"] = "hatching chick bird egg",
        ["🐥"] = "front facing baby chick bird",
        ["🦆"] = "duck bird quack",
        ["🦅"] = "eagle bird america",
        ["🦉"] = "owl bird night wise",
        ["🦇"] = "bat vampire halloween",
        ["🐺"] = "wolf face howl",
        ["🐗"] = "boar pig wild",
        ["🐴"] = "horse face pony",
        ["🦄"] = "unicorn face magic rainbow",
        ["🐝"] = "honeybee bee buzz wasp",
        ["🪱"] = "worm earthworm",
        ["🐛"] = "bug caterpillar insect",
        ["🦋"] = "butterfly insect beautiful",
        ["🐌"] = "snail slow shell",
        ["🐞"] = "lady beetle bug ladybug",
        ["🐜"] = "ant insect",
        ["🪰"] = "fly insect bug",
        ["🪲"] = "beetle insect bug",
        ["🪳"] = "cockroach roach bug insect",
        ["🦟"] = "mosquito bug insect bite",
        ["🦗"] = "cricket insect chirp",
        ["🕷️"] = "spider web arachnid",
        ["🦂"] = "scorpion sting",
        ["🐢"] = "turtle tortoise slow shell",
        ["🐍"] = "snake serpent",
        ["🦎"] = "lizard reptile gecko",
        ["🦖"] = "t-rex dinosaur tyrannosaurus",
        ["🦕"] = "sauropod dinosaur brontosaurus",
        ["🐙"] = "octopus tentacle sea",
        ["🦑"] = "squid tentacle sea",
        ["🦐"] = "shrimp prawn seafood",
        ["🦞"] = "lobster seafood",
        ["🦀"] = "crab seafood",
        ["🐡"] = "blowfish puffer fish",
        ["🐠"] = "tropical fish sea",
        ["🐟"] = "fish sea",
        ["🐬"] = "dolphin flipper sea",
        ["🐳"] = "spouting whale sea ocean",
        ["🐋"] = "whale sea ocean",
        ["\U0001FACD"] = "orca killer whale sea ocean",
        ["🦈"] = "shark fish sea jaws",
        ["🐊"] = "crocodile alligator reptile",
        ["🐅"] = "tiger cat stripes",
        ["🐆"] = "leopard cat spots cheetah",
        ["🦓"] = "zebra stripes horse",
        ["🦍"] = "gorilla ape primate",
        ["🦧"] = "orangutan ape primate",
        ["🐘"] = "elephant trunk safari",

        // Nature
        ["🌸"] = "cherry blossom flower pink spring",
        ["💐"] = "bouquet flowers",
        ["🌹"] = "rose flower red love",
        ["🥀"] = "wilted flower dead rose",
        ["🌺"] = "hibiscus flower tropical",
        ["🌻"] = "sunflower flower sun",
        ["🌼"] = "blossom flower bloom",
        ["🌷"] = "tulip flower spring",
        ["🌱"] = "seedling sprout plant grow",
        ["🪴"] = "potted plant houseplant",
        ["🌲"] = "evergreen tree pine christmas",
        ["🌳"] = "deciduous tree oak",
        ["🌴"] = "palm tree tropical beach",
        ["🌵"] = "cactus desert",
        ["🍀"] = "four leaf clover luck lucky",
        ["☘️"] = "shamrock clover irish",
        ["🍁"] = "maple leaf fall autumn canada",
        ["🍂"] = "fallen leaf autumn fall",
        ["🍃"] = "leaf fluttering wind blowing",
        ["🌾"] = "sheaf rice grain wheat",
        ["🍄"] = "mushroom fungus toadstool",
        ["🌿"] = "herb leaf plant green",
        ["☀️"] = "sun sunny bright hot",
        ["🌤️"] = "sun small cloud partly sunny",
        ["⛅"] = "sun behind cloud partly cloudy",
        ["🌥️"] = "sun behind large cloud mostly cloudy",
        ["🌦️"] = "sun behind rain cloud",
        ["🌧️"] = "cloud rain rainy",
        ["⛈️"] = "cloud lightning rain thunderstorm storm",
        ["🌩️"] = "cloud lightning thunder",
        ["🌨️"] = "cloud snow snowing",
        ["❄️"] = "snowflake cold winter ice frozen",
        ["☃️"] = "snowman snow winter cold",
        ["⛄"] = "snowman without snow winter",
        ["🌪️"] = "tornado twister cyclone",
        ["🌫️"] = "fog foggy mist haze",
        ["🌊"] = "water wave ocean sea surf",
        ["💧"] = "droplet water tear rain",
        ["💦"] = "sweat droplets splash water",
        ["💨"] = "dashing away wind fast rush gone leaving",
        ["🌈"] = "rainbow colors spectrum pride",
        ["☁️"] = "cloud cloudy overcast",
        ["⚡"] = "high voltage lightning zap electricity thunder bolt",
        ["💥"] = "collision boom explosion bang",
        ["☄️"] = "comet shooting star space",
        ["⭐"] = "star yellow gold",
        ["🌟"] = "glowing star sparkle shine",
        ["✨"] = "sparkles shine glitter magic stars",
        ["🌑"] = "new moon dark",
        ["🌒"] = "waxing crescent moon",
        ["🌓"] = "first quarter moon half",
        ["🌔"] = "waxing gibbous moon",
        ["🌕"] = "full moon bright",
        ["🌖"] = "waning gibbous moon",
        ["🌗"] = "last quarter moon half",
        ["🌘"] = "waning crescent moon",
        ["🌙"] = "crescent moon night",
        ["🌚"] = "new moon face dark",
        ["🌛"] = "first quarter moon face",
        ["🌜"] = "last quarter moon face",
        ["🌝"] = "full moon face bright",
        ["🌞"] = "sun face sunny bright",

        // Food
        ["🍏"] = "green apple fruit",
        ["🍎"] = "red apple fruit",
        ["🍐"] = "pear fruit",
        ["🍊"] = "tangerine orange citrus fruit",
        ["🍋"] = "lemon citrus fruit sour",
        ["🍌"] = "banana fruit",
        ["🍉"] = "watermelon fruit summer",
        ["🍇"] = "grapes fruit wine",
        ["🍓"] = "strawberry fruit berry",
        ["🫐"] = "blueberries fruit berry",
        ["🍈"] = "melon fruit cantaloupe",
        ["🍒"] = "cherries fruit cherry",
        ["🍑"] = "peach fruit",
        ["🥭"] = "mango fruit tropical",
        ["🍍"] = "pineapple fruit tropical",
        ["🥥"] = "coconut tropical",
        ["🥝"] = "kiwi fruit",
        ["🍅"] = "tomato fruit vegetable",
        ["🍆"] = "eggplant aubergine vegetable",
        ["🥑"] = "avocado fruit guacamole",
        ["🥦"] = "broccoli vegetable green",
        ["🥬"] = "leafy green lettuce vegetable",
        ["🥒"] = "cucumber vegetable pickle",
        ["🌶️"] = "hot pepper chili spicy",
        ["🫑"] = "bell pepper vegetable",
        ["🌽"] = "corn maize vegetable",
        ["🥕"] = "carrot vegetable orange",
        ["🫒"] = "olive oil vegetable",
        ["🧄"] = "garlic vegetable",
        ["🧅"] = "onion vegetable",
        ["🥔"] = "potato vegetable",
        ["🍠"] = "sweet potato roasted yam",
        ["🥐"] = "croissant bread french pastry",
        ["🥯"] = "bagel bread",
        ["🍞"] = "bread loaf toast",
        ["🥖"] = "baguette bread french",
        ["🥨"] = "pretzel snack",
        ["🧀"] = "cheese wedge",
        ["🥚"] = "egg breakfast",
        ["🍳"] = "cooking egg fried breakfast",
        ["🧈"] = "butter dairy",
        ["🥞"] = "pancakes breakfast stack",
        ["🧇"] = "waffle breakfast",
        ["🥓"] = "bacon meat breakfast",
        ["🥩"] = "cut meat steak beef",
        ["🍗"] = "poultry leg chicken drumstick",
        ["🍖"] = "meat bone rib",
        ["🦴"] = "bone dog skeleton",
        ["🌭"] = "hot dog sausage",
        ["🍔"] = "hamburger burger cheeseburger fast food",
        ["🍟"] = "french fries chips fast food",
        ["🍕"] = "pizza slice cheese",
        ["🫓"] = "flatbread naan pita",
        ["🥪"] = "sandwich sub",
        ["🥙"] = "stuffed flatbread pita falafel",
        ["🧆"] = "falafel middle eastern",
        ["🌮"] = "taco mexican",
        ["🌯"] = "burrito wrap mexican",
        ["🫔"] = "tamale mexican",
        ["🥗"] = "green salad bowl healthy",
        ["🥘"] = "shallow pan food paella cooking",
        ["🫕"] = "fondue cheese pot",
        ["🍝"] = "spaghetti pasta italian noodles",
        ["🍜"] = "steaming bowl noodles ramen soup",
        ["🍲"] = "pot food stew",
        ["🍛"] = "curry rice indian",
        ["🍣"] = "sushi japanese fish",
        ["🍱"] = "bento box japanese lunch",
        ["🥟"] = "dumpling dim sum gyoza",
        ["🦪"] = "oyster shellfish pearl",
        ["🍤"] = "fried shrimp tempura prawn",
        ["🍙"] = "rice ball onigiri japanese",
        ["🍚"] = "cooked rice bowl",
        ["🍘"] = "rice cracker japanese",
        ["🍥"] = "fish cake swirl narutomaki",
        ["🥠"] = "fortune cookie chinese",
        ["🥮"] = "moon cake chinese",
        ["🍢"] = "oden skewer japanese",
        ["🍡"] = "dango japanese sweet",
        ["🍧"] = "shaved ice dessert",
        ["🍨"] = "ice cream sundae dessert",
        ["🍦"] = "soft ice cream cone dessert",
        ["🥧"] = "pie dessert thanksgiving",
        ["🧁"] = "cupcake muffin dessert",
        ["🍰"] = "shortcake cake slice dessert",
        ["🎂"] = "birthday cake celebration dessert",
        ["🍮"] = "custard pudding flan dessert",
        ["🍭"] = "lollipop candy sweet",
        ["🍬"] = "candy sweet wrapper",
        ["🍫"] = "chocolate bar candy sweet",
        ["🍿"] = "popcorn movie snack drama watching gossip spectator entertained tea",
        ["🍩"] = "doughnut donut sweet dessert",
        ["🍪"] = "cookie biscuit sweet",
        ["🌰"] = "chestnut nut",
        ["🥜"] = "peanuts nut",
        ["🍯"] = "honey pot sweet bee",
        ["☕"] = "hot beverage coffee tea cup",
        ["🍵"] = "teacup tea green matcha spilling the tea gossip drama",
        ["🧃"] = "beverage box juice",
        ["🥛"] = "glass milk drink",
        ["🍼"] = "baby bottle milk",
        ["🫖"] = "teapot tea",
        ["🧋"] = "bubble tea boba milk tea",
        ["🍶"] = "sake japanese rice wine",
        ["🍺"] = "beer mug drink",
        ["🍻"] = "clinking beer mugs cheers drink",
        ["🥂"] = "clinking glasses champagne toast cheers",
        ["🍷"] = "wine glass red drink",

        // Activities
        ["⚽"] = "soccer ball football sport",
        ["🏀"] = "basketball sport ball",
        ["🏈"] = "american football sport ball",
        ["⚾"] = "baseball sport ball",
        ["🥎"] = "softball sport ball",
        ["🎾"] = "tennis sport ball racquet",
        ["🏐"] = "volleyball sport ball",
        ["🏉"] = "rugby football sport ball",
        ["🥏"] = "flying disc frisbee sport",
        ["🎱"] = "pool billiards 8 ball",
        ["🪀"] = "yo-yo toy",
        ["🏓"] = "ping pong table tennis sport",
        ["🏸"] = "badminton sport shuttlecock",
        ["🏒"] = "ice hockey sport stick puck",
        ["🏑"] = "field hockey sport stick",
        ["🥍"] = "lacrosse sport stick",
        ["🏏"] = "cricket sport bat",
        ["🪃"] = "boomerang throw return",
        ["🥅"] = "goal net sport",
        ["⛳"] = "flag hole golf sport",
        ["🪁"] = "kite fly wind",
        ["🏹"] = "bow arrow archery",
        ["🎣"] = "fishing pole rod",
        ["🤿"] = "diving mask snorkel scuba",
        ["🥊"] = "boxing glove fight sport",
        ["🥋"] = "martial arts karate judo",
        ["🎽"] = "running shirt sport",
        ["🛹"] = "skateboard sport",
        ["🛼"] = "roller skate",
        ["🛷"] = "sled toboggan winter",
        ["⛸️"] = "ice skate winter sport",
        ["🥌"] = "curling stone winter sport",
        ["🎿"] = "skis winter sport snow",
        ["⛷️"] = "skier winter sport snow",
        ["🏂"] = "snowboarder winter sport snow",
        ["🪂"] = "parachute skydiving",
        ["🏋️"] = "person lifting weights gym workout",
        ["🏋️‍♂️"] = "man lifting weights gym workout male bodybuilder strong",
        ["🏋️‍♀️"] = "woman lifting weights gym workout female bodybuilder strong",
        ["🤼"] = "people wrestling sport",
        ["🤸"] = "person cartwheeling gymnastics",
        ["🤺"] = "person fencing sword sport",
        ["⛹️"] = "person bouncing ball basketball",
        ["🤾"] = "person playing handball sport",
        ["🏌️"] = "person golfing sport",
        ["🏇"] = "horse racing jockey sport",
        ["🧘"] = "person lotus position yoga meditation",
        ["🏄"] = "person surfing wave sport",
        ["🏊"] = "person swimming sport pool",
        ["🤽"] = "person playing water polo sport",
        ["🚣"] = "person rowing boat sport",
        ["🧗"] = "person climbing rock sport",
        ["🚵"] = "person mountain biking sport",
        ["🚴"] = "person biking cycling sport",
        ["🏃"] = "person running run hurry rush late sprint",
        ["🏆"] = "trophy winner champion cup",
        ["🥇"] = "1st place medal gold first winner",
        ["🥈"] = "2nd place medal silver second",
        ["🥉"] = "3rd place medal bronze third",
        ["🏅"] = "sports medal",
        ["🎖️"] = "military medal honor",
        ["🏵️"] = "rosette award",
        ["🎗️"] = "reminder ribbon awareness",
        ["🎫"] = "ticket admission",
        ["🎟️"] = "admission tickets event",
        ["🎪"] = "circus tent",
        ["🎭"] = "performing arts theater drama masks",
        ["🎨"] = "artist palette paint art",
        ["🎬"] = "clapper board movie film",
        ["🎤"] = "microphone karaoke sing",
        ["🎧"] = "headphone music audio listen",
        ["🎼"] = "musical score notes sheet music",
        ["🎵"] = "musical note music song tune melody singing",
        ["🎶"] = "musical notes music song tune melody singing",
        ["🎹"] = "musical keyboard piano keys",
        ["🥁"] = "drum drumsticks percussion",
        ["🪘"] = "long drum percussion",
        ["🎷"] = "saxophone jazz music",
        ["🎺"] = "trumpet brass music",
        ["📯"] = "postal horn bugle brass music",
        ["🪗"] = "accordion music",
        ["🎸"] = "guitar music rock electric",
        ["🪕"] = "banjo music string",
        ["🪉"] = "harp music string orchestra",
        ["🎻"] = "violin fiddle cello music string orchestra",
        ["🪈"] = "flute pipe recorder woodwind music",
        ["🪇"] = "maracas shaker rattle percussion music",
        ["🎲"] = "game die dice roll",
        ["♟️"] = "chess pawn piece game",
        ["🎯"] = "bullseye target dart",
        ["🎳"] = "bowling ball pins sport",
        ["🎮"] = "video game controller joystick",
        ["🎰"] = "slot machine casino gambling",

        // Travel
        ["🚗"] = "automobile car red vehicle",
        ["🚕"] = "taxi cab yellow car",
        ["🚙"] = "sport utility vehicle suv car",
        ["🚌"] = "bus transit public",
        ["🚎"] = "trolleybus transit",
        ["🏎️"] = "racing car formula speed",
        ["🚓"] = "police car law",
        ["🚑"] = "ambulance emergency medical",
        ["🚒"] = "fire engine truck emergency",
        ["🚐"] = "minibus van",
        ["🛻"] = "pickup truck",
        ["🚚"] = "delivery truck moving",
        ["🚛"] = "articulated lorry truck semi",
        ["🚜"] = "tractor farm vehicle",
        ["🏍️"] = "motorcycle racing bike",
        ["🛵"] = "motor scooter vespa",
        ["🚲"] = "bicycle bike cycling",
        ["🛴"] = "kick scooter",
        ["🛺"] = "auto rickshaw tuk tuk",
        ["🚨"] = "police car light siren emergency",
        ["🚔"] = "oncoming police car",
        ["🚍"] = "oncoming bus",
        ["🚘"] = "oncoming automobile car",
        ["🚖"] = "oncoming taxi",
        ["🚡"] = "aerial tramway cable car",
        ["🚠"] = "mountain cableway gondola",
        ["🚟"] = "suspension railway monorail",
        ["🚃"] = "railway car train",
        ["🚋"] = "tram streetcar trolley",
        ["🚞"] = "mountain railway train",
        ["🚝"] = "monorail train",
        ["🚄"] = "high speed train bullet",
        ["🚅"] = "bullet train speed",
        ["🚈"] = "light rail train",
        ["🚂"] = "locomotive steam train engine",
        ["🚆"] = "train",
        ["🚇"] = "metro subway underground train",
        ["🚊"] = "tram streetcar",
        ["🚉"] = "station train platform",
        ["✈️"] = "airplane plane fly travel",
        ["🛫"] = "airplane departure takeoff fly",
        ["🛬"] = "airplane arrival landing fly",
        ["🛩️"] = "small airplane plane",
        ["💺"] = "seat chair airplane",
        ["🛰️"] = "satellite space orbit",
        ["🚀"] = "rocket space launch",
        ["🛸"] = "flying saucer ufo alien space",
        ["🚁"] = "helicopter chopper fly",
        ["🛶"] = "canoe kayak paddle boat",
        ["⛵"] = "sailboat sail boat wind",
        ["🚤"] = "speedboat fast boat",
        ["🛥️"] = "motor boat yacht",
        ["🛳️"] = "passenger ship cruise liner",
        ["⛴️"] = "ferry boat ship",
        ["🚢"] = "ship boat sea",
        ["⚓"] = "anchor ship boat nautical",
        ["🪝"] = "hook fishing catch",
        ["⛽"] = "fuel pump gas station",
        ["🚧"] = "construction sign barrier",
        ["🚦"] = "vertical traffic light",
        ["🚥"] = "horizontal traffic light",
        ["🗿"] = "moai easter island stone statue",
        ["🗽"] = "statue liberty new york",
        ["🗼"] = "tokyo tower japan",
        ["🏰"] = "castle european medieval",
        ["🏯"] = "japanese castle",
        ["🏟️"] = "stadium arena sport",
        ["🎡"] = "ferris wheel carnival amusement",
        ["🎢"] = "roller coaster amusement park",
        ["🎠"] = "carousel horse merry go round",
        ["⛲"] = "fountain water park",
        ["⛱️"] = "umbrella ground beach sun",
        ["🏖️"] = "beach umbrella sand sun vacation",
        ["🏝️"] = "desert island tropical palm",
        ["🏜️"] = "desert sand dry",
        ["🌋"] = "volcano eruption lava mountain",
        ["⛰️"] = "mountain peak",
        ["🏔️"] = "snow capped mountain",
        ["🗻"] = "mount fuji japan mountain",
        ["🏕️"] = "camping tent outdoor",
        ["🛖"] = "hut shelter house",
        ["🏠"] = "house home building",
        ["🏡"] = "house garden home",
        ["🏘️"] = "houses buildings neighborhood",

        // Objects
        ["⌚"] = "watch time wrist clock",
        ["📱"] = "mobile phone cell smartphone",
        ["💻"] = "laptop computer",
        ["⌨️"] = "keyboard type computer",
        ["🖥️"] = "desktop computer monitor screen",
        ["🖨️"] = "printer print",
        ["🖱️"] = "computer mouse click",
        ["🖲️"] = "trackball",
        ["💽"] = "computer disk minidisc",
        ["💾"] = "floppy disk save",
        ["💿"] = "optical disk cd",
        ["📀"] = "dvd disc",
        ["📼"] = "videocassette vhs tape",
        ["📷"] = "camera photo",
        ["📸"] = "camera flash photo",
        ["📹"] = "video camera record",
        ["🎥"] = "movie camera film",
        ["📽️"] = "film projector movie",
        ["🎞️"] = "film frames movie",
        ["📞"] = "telephone receiver phone call",
        ["☎️"] = "telephone phone call",
        ["📟"] = "pager beeper",
        ["📠"] = "fax machine",
        ["📺"] = "television tv screen",
        ["📻"] = "radio broadcast",
        ["🎙️"] = "studio microphone podcast record",
        ["🎚️"] = "level slider volume",
        ["🎛️"] = "control knobs dial",
        ["🧭"] = "compass navigation direction",
        ["⏱️"] = "stopwatch timer",
        ["⏲️"] = "timer clock",
        ["⏰"] = "alarm clock wake up",
        ["🕰️"] = "mantelpiece clock",
        ["⌛"] = "hourglass sand timer wait",
        ["⏳"] = "hourglass flowing sand timer",
        ["📡"] = "satellite antenna dish signal",
        ["🔋"] = "battery power charge",
        ["🪫"] = "low battery empty drained dead tired no energy",
        ["🔌"] = "electric plug power charge",
        ["💡"] = "light bulb idea bright",
        ["🔦"] = "flashlight torch light",
        ["🕯️"] = "candle light flame",
        ["🪔"] = "diya lamp oil light",
        ["🔥"] = "fire flame hot burn lit",
        ["🧯"] = "fire extinguisher safety",
        ["🛢️"] = "oil drum barrel",
        ["💸"] = "money wings fly cash",
        ["💵"] = "dollar banknote money cash",
        ["💴"] = "yen banknote money japanese",
        ["💶"] = "euro banknote money",
        ["💷"] = "pound banknote money british",
        ["🪙"] = "coin money gold",
        ["💰"] = "money bag cash rich",
        ["💳"] = "credit card payment",
        ["💎"] = "gem stone diamond jewel",
        ["⚖️"] = "balance scale justice law",
        ["🪜"] = "ladder climb step",
        ["🧰"] = "toolbox tools repair",
        ["🪛"] = "screwdriver tool fix",
        ["🔧"] = "wrench tool fix spanner",
        ["🔨"] = "hammer tool build",
        ["⚒️"] = "hammer pick tool mine",
        ["🛠️"] = "hammer wrench tool fix repair",
        ["⛏️"] = "pick tool mine",
        ["🪚"] = "carpentry saw tool cut wood",
        ["🔩"] = "nut bolt screw",
        ["⚙️"] = "gear cog settings",
        ["🪤"] = "mouse trap",
        ["🧱"] = "brick wall build",
        ["⛓️"] = "chains link lock",
        ["🧲"] = "magnet attract",
        ["🔫"] = "water pistol gun",
        ["💣"] = "bomb explosion",
        ["🧨"] = "firecracker dynamite explosive",
        ["🪓"] = "axe chop wood tool",
        ["🔪"] = "kitchen knife blade cut",
        ["🗡️"] = "dagger sword blade",
        ["⚔️"] = "crossed swords fight battle",
        ["🛡️"] = "shield defense protect",
        ["🚬"] = "cigarette smoking",
        ["⚰️"] = "coffin death funeral",
        ["🪦"] = "headstone grave cemetery",
        ["⚱️"] = "funeral urn ashes",
        ["🏺"] = "amphora vase pottery",
        ["🔮"] = "crystal ball fortune magic",
        ["📿"] = "prayer beads rosary",
        ["🔑"] = "key lock password",
        ["🗝️"] = "old key vintage skeleton",
        ["🔒"] = "locked lock secure padlock",
        ["🔓"] = "unlocked lock open padlock",
        ["📦"] = "package box delivery parcel",
        ["✉️"] = "envelope mail letter email",
        ["📝"] = "memo note write pencil paper",
        ["📖"] = "open book read reading",
        ["📚"] = "books stack library study",
        ["📉"] = "chart decreasing down decline loss falling worse",
        ["🔔"] = "bell notification alert ring",
        ["🔕"] = "bell slash mute silent no notification",
        ["📢"] = "loudspeaker announcement public",
        ["📣"] = "megaphone cheering announcement",
        ["🎁"] = "wrapped gift present birthday christmas",
        ["🎀"] = "ribbon bow decoration pink",
        ["🎈"] = "balloon party celebration birthday",
        ["🎉"] = "party popper tada celebration confetti",
        ["🎊"] = "confetti ball celebration party",
        ["✏️"] = "pencil write edit",
        ["✂️"] = "scissors cut",
        ["📎"] = "paperclip clip attachment",
        ["🧸"] = "teddy bear toy stuffed",
        ["🚪"] = "door entrance exit room",
        ["🛏️"] = "bed sleep bedroom rest",
        ["🛋️"] = "couch lamp living room sofa",
        ["🚿"] = "shower water bathroom",
        ["🛁"] = "bathtub bath soak",
        ["🪞"] = "mirror reflection",
        ["🪑"] = "chair seat sit",
        ["🧩"] = "puzzle piece jigsaw",

        // Symbols
        ["❣️"] = "heart exclamation love",
        ["☮️"] = "peace symbol sign",
        ["✝️"] = "latin cross christian religion",
        ["☪️"] = "star crescent islam religion",
        ["🕉️"] = "om hindu religion",
        ["☸️"] = "wheel dharma buddhism religion",
        ["✡️"] = "star david jewish religion",
        ["🔯"] = "dotted six pointed star",
        ["🕎"] = "menorah hanukkah jewish candle",
        ["☯️"] = "yin yang balance tao",
        ["☦️"] = "orthodox cross religion",
        ["🛐"] = "place worship prayer religion",
        ["⛎"] = "ophiuchus zodiac",
        ["♈"] = "aries zodiac",
        ["♉"] = "taurus zodiac",
        ["♊"] = "gemini zodiac",
        ["♋"] = "cancer zodiac",
        ["♌"] = "leo zodiac",
        ["♍"] = "virgo zodiac",
        ["♎"] = "libra zodiac",
        ["♏"] = "scorpio zodiac",
        ["♐"] = "sagittarius zodiac",
        ["♑"] = "capricorn zodiac",
        ["♒"] = "aquarius zodiac",
        ["♓"] = "pisces zodiac",
        ["🆔"] = "id squared identity",
        ["⚛️"] = "atom symbol science",
        ["🉑"] = "japanese acceptable kanji",
        ["☢️"] = "radioactive nuclear radiation",
        ["☣️"] = "biohazard biological hazard",
        ["📴"] = "mobile phone off silent",
        ["📳"] = "vibration mode phone",
        ["🈶"] = "japanese have kanji",
        ["🈚"] = "japanese free charge kanji",
        ["🈸"] = "japanese application kanji",
        ["🈺"] = "japanese open business kanji",
        ["🈷️"] = "japanese monthly amount kanji",
        ["✴️"] = "eight pointed star",
        ["🆚"] = "vs versus against",
        ["💮"] = "white flower brilliant",
        ["🉐"] = "japanese bargain kanji",
        ["㊙️"] = "japanese secret kanji",
        ["㊗️"] = "japanese congratulations kanji",
        ["🈴"] = "japanese passing grade kanji",
        ["🈵"] = "japanese full kanji",
        ["🈹"] = "japanese discount kanji",
        ["🈲"] = "japanese prohibited kanji",
        ["🅰️"] = "a button blood type",
        ["🅱️"] = "b button blood type",
        ["🆎"] = "ab button blood type",
        ["🆑"] = "cl button clear",
        ["🅾️"] = "o button blood type",
        ["🆘"] = "sos help emergency",
        ["❌"] = "cross mark wrong no delete",
        ["⭕"] = "hollow red circle",
        ["🛑"] = "stop sign octagonal",
        ["⛔"] = "no entry forbidden",
        ["📛"] = "name badge",
        ["🚫"] = "prohibited forbidden ban no",
        ["💯"] = "hundred percent 100 perfect score",
        ["💢"] = "anger symbol mad",
        ["♨️"] = "hot springs steam",
        ["🚷"] = "no pedestrians",
        ["🚯"] = "no littering",
        ["🚳"] = "no bicycles",
        ["🚱"] = "non potable water",
        ["🔞"] = "no one under eighteen adult 18",
        ["📵"] = "no mobile phones",
        ["🚭"] = "no smoking",
        ["❗"] = "exclamation mark warning red",
        ["❓"] = "question mark red",
        ["‼️"] = "double exclamation mark",
        ["⁉️"] = "exclamation question mark",
        ["🔅"] = "dim button brightness low",
        ["🔆"] = "bright button brightness high",
        ["〽️"] = "part alternation mark",
        ["⚠️"] = "warning sign caution yellow triangle",
        ["🚸"] = "children crossing school zone",
        ["🔱"] = "trident emblem",
        ["⚜️"] = "fleur de lis",
        ["🔰"] = "japanese symbol beginner",
        ["♻️"] = "recycling symbol recycle green",
        ["✅"] = "check mark button done yes green",
        ["🈯"] = "japanese reserved kanji",
        ["💹"] = "chart increasing yen stocks",
        ["❇️"] = "sparkle star",
        ["✳️"] = "eight spoked asterisk star",
        ["❎"] = "cross mark button no",
        ["🌐"] = "globe meridians earth world internet",
        ["💠"] = "diamond dot cute",

        // Flags
        ["🏳️"] = "white flag surrender peace",
        ["🏴"] = "black flag",
        ["🏁"] = "chequered flag checkered race finish",
        ["🚩"] = "triangular flag red flag",
        ["🏳️‍🌈"] = "rainbow flag pride lgbtq",
        ["🏳️‍⚧️"] = "transgender flag pride trans",
        ["🏴‍☠️"] = "pirate flag skull jolly roger",
        ["🇺🇸"] = "united states flag usa america",
        ["🇬🇧"] = "united kingdom flag uk britain england",
        ["🇨🇦"] = "canada flag maple",
        ["🇦🇺"] = "australia flag",
        ["🇩🇪"] = "germany flag deutsch",
        ["🇫🇷"] = "france flag french",
        ["🇮🇹"] = "italy flag italian",
        ["🇪🇸"] = "spain flag spanish",
        ["🇯🇵"] = "japan flag japanese",
        ["🇰🇷"] = "south korea flag korean",
        ["🇨🇳"] = "china flag chinese",
        ["🇷🇺"] = "russia flag russian",
        ["🇧🇷"] = "brazil flag brazilian",
        ["🇲🇽"] = "mexico flag mexican",
        ["🇮🇳"] = "india flag indian",
        ["🇳🇱"] = "netherlands flag dutch",
        ["🇧🇪"] = "belgium flag belgian",
        ["🇨🇭"] = "switzerland flag swiss",
        ["🇦🇹"] = "austria flag austrian",
        ["🇸🇪"] = "sweden flag swedish",
        ["🇳🇴"] = "norway flag norwegian",
        ["🇩🇰"] = "denmark flag danish",
        ["🇫🇮"] = "finland flag finnish",
        ["🇵🇱"] = "poland flag polish",
        ["🇺🇦"] = "ukraine flag ukrainian",
        ["🇬🇷"] = "greece flag greek",
        ["🇹🇷"] = "turkey flag turkish",
        ["🇮🇱"] = "israel flag",
        ["🇸🇦"] = "saudi arabia flag",
        ["🇮🇶"] = "iraq flag iraqi",
        ["🇦🇪"] = "united arab emirates flag uae dubai",
        ["🇪🇬"] = "egypt flag egyptian",
        ["🇿🇦"] = "south africa flag",
        ["🇳🇬"] = "nigeria flag nigerian",
        ["🇰🇪"] = "kenya flag kenyan",
        ["🇦🇷"] = "argentina flag",
        ["🇨🇴"] = "colombia flag colombian",
        ["🇨🇱"] = "chile flag chilean",
        ["🇵🇪"] = "peru flag peruvian",
        ["🇻🇪"] = "venezuela flag",
        ["🇵🇭"] = "philippines flag filipino",
        ["🇮🇩"] = "indonesia flag indonesian",
        ["🇹🇭"] = "thailand flag thai",
        ["🇻🇳"] = "vietnam flag vietnamese",
        ["🇲🇾"] = "malaysia flag malaysian",
        ["🇸🇬"] = "singapore flag",
        ["🇳🇿"] = "new zealand flag kiwi",
        ["🇮🇪"] = "ireland flag irish",
        ["🇵🇹"] = "portugal flag portuguese",
        ["🇨🇿"] = "czech republic flag",
        ["🇭🇺"] = "hungary flag hungarian",
        ["🇷🇴"] = "romania flag romanian",
        ["🇧🇬"] = "bulgaria flag bulgarian",
    };

}
