#!/usr/bin/env python3
"""Build tools/letter-ngrams-{en,cs}.js from an OPUS OpenSubtitles dump.

Usage:
  python3 tools/build-letter-ngrams.py en tools/corpus/os-en-83886080.txt.gz
  python3 tools/build-letter-ngrams.py cs tools/corpus/os-cs-83886080.txt.gz

These are LETTER bigrams/trigrams (th, he, in / the, and, ing), not the
word bigrams in bigrams-{en,cs}.js. Nothing at runtime reads them; they
exist so tools/score-flow.mjs can measure how well a layout's gestures
flow into each other. See layout-flow-analysis.md.

Why derive them here instead of copying a published table: no published
letter-bigram table exists for Czech, and the two languages must be
measured the same way to be comparable.

Cross-checked against Norvig's Google Books table
(tools/norvig-bigrams.json): 83 of our top 100 pairs are also in his
top 100, Spearman 0.61 on the shared set. The 17 that differ are the
spoken/literary split, not an error. We gain yo do go ay oo gh ck ey
(you, do, go, okay, look, right, back, they) and lose io ns ec pr ct
tr nc (-tion, -ness, pro-, -ction). Subtitles are the better model of
phone typing, which is why this repo already uses them for the word
predictor. tools/score-flow.mjs scores English against both tables and
reports whether the layout ranking survives the swap.

Method notes, each one a decision that changes the numbers:
- The tokenizer is imported from build-wordlists.py, never re-written,
  so the letter tables and the word lists always describe the same
  token stream.
- Counting runs over the FULL word counter, not its top-3000 slice, so
  a pair is weighted by every occurrence in the corpus.
- Within-word pairs only. Between two words the finger sits in the
  center for the space, so a cross-word pair is not a two-loop shape
  at all and would pollute the flow measurement.
- Apostrophes split a word ("don't" -> "don", "t"). The apostrophe is
  not on the letter layouts, so "n't" must not invent an "nt" pair.
- Czech diacritics fold to base letters BEFORE extraction, because the
  end-state keyboard is one combined en+cs layout with no diacritic
  keys. Folding first merges "ří" into "ri" rather than counting them
  as two pairs that only one of them can be typed as.
"""
import json
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from importlib import import_module

count_words = import_module('build-wordlists').count_words

TOP_N = 100

# Folded before extraction, see the module docstring. Base-letter
# targets only: the combined layout has no diacritic slots.
FOLD = str.maketrans({
    'á': 'a', 'č': 'c', 'ď': 'd', 'é': 'e', 'ě': 'e', 'í': 'i', 'ň': 'n',
    'ó': 'o', 'ř': 'r', 'š': 's', 'ť': 't', 'ú': 'u', 'ů': 'u', 'ý': 'y',
    'ž': 'z',
})


def ngrams_from_words(counts, n):
    """Letter n-grams over the token stream, weighted by word count."""
    out = Counter()
    for word, c in counts.items():
        folded = word.translate(FOLD)
        # An apostrophe is a hard break, not a letter: see docstring.
        for part in folded.split("'"):
            for i in range(len(part) - n + 1):
                out[part[i:i + n]] += c
    return out


def table(counts, n):
    grams = ngrams_from_words(counts, n)
    top = grams.most_common(TOP_N)
    return {
        'top': [[g, c] for g, c in top],
        'topTotal': sum(c for _, c in top),
        'corpusTotal': sum(grams.values()),
        'distinct': len(grams),
    }


def main():
    lang, dump_path = sys.argv[1], sys.argv[2]
    out_path = Path(__file__).resolve().parent / f'letter-ngrams-{lang}.js'

    counts, lines = count_words(lang, dump_path)
    bi = table(counts, 2)
    tri = table(counts, 3)

    header = (
        "// Generated by tools/build-letter-ngrams.py from the OPUS\n"
        "// OpenSubtitles v2018 mono dump (attribution:\n"
        "// https://www.opensubtitles.org). LETTER bigrams and trigrams,\n"
        f"// top {TOP_N} of each, as [gram, count]. Not word bigrams: those\n"
        "// are bigrams-{en,cs}.js and are a different thing.\n"
        "// Within-word only, apostrophe-split, cs diacritics folded to\n"
        "// base letters. Read by tools/score-flow.mjs; no runtime code\n"
        "// uses this file. See layout-flow-analysis.md.\n"
        f"// Corpus: {lines} lines, {sum(counts.values())} tokens.\n"
    )
    body = (
        f"export const BIGRAMS = {json.dumps(bi, ensure_ascii=False, separators=(',', ':'))};\n"
        f"export const TRIGRAMS = {json.dumps(tri, ensure_ascii=False, separators=(',', ':'))};\n"
    )
    out_path.write_text(header + body, encoding='utf-8')

    print(f"{lang}: {lines} lines, {sum(counts.values())} tokens, "
          f"{len(counts)} distinct words -> {out_path.name}")
    print(f"  bigrams:  {bi['distinct']} distinct, top {TOP_N} cover "
          f"{100 * bi['topTotal'] / bi['corpusTotal']:.1f}% of all pairs")
    print("   ", ' '.join(g for g, _ in bi['top'][:20]))
    print(f"  trigrams: {tri['distinct']} distinct, top {TOP_N} cover "
          f"{100 * tri['topTotal'] / tri['corpusTotal']:.1f}% of all triples")
    print("   ", ' '.join(g for g, _ in tri['top'][:20]))


if __name__ == '__main__':
    main()
