#!/usr/bin/env python3
"""Build bigrams-en.js / bigrams-cs.js from an OPUS OpenSubtitles dump.

Usage:
  python3 tools/build-ngrams.py en os_en.txt.gz words-en.js bigrams-en.js
  python3 tools/build-ngrams.py cs os_cs.txt.gz words-cs.js bigrams-cs.js

Input: the same monolingual OpenSubtitles v2018 dump as
tools/build-wordlists.py (see its docstring for URLs). A
range-truncated download (first ~80 MB) is fine and is what the
measured tables in word-prediction-research.md came from.
Attribution: https://www.opensubtitles.org

Output: {head: [w1..w5]} in rank order, heads in vocabulary frequency
order. Words only, no counts: counts triple the size and add nothing
for ranking a five-chip strip (word-prediction-research.md, table
notes).

Rules:
- Tokenization is imported from build-wordlists.py, so the two files
  can never drift apart. The shared tools/textnorm.py extraction is
  planned with the personalization work.
- A pair counts only when both words are vocabulary entries and the
  tokens are adjacent. An out-of-vocabulary or junk token between two
  words breaks adjacency; so does clause-ending punctuation (.!?…)
  after the first word ("no. you go" must not teach "no -> you").
- A pair needs MIN_PAIR occurrences; below that a rare head's top-5
  fills with one-off noise.
"""
import gzip
import importlib.util
import json
import sys
from collections import Counter
from pathlib import Path

spec = importlib.util.spec_from_file_location(
    'build_wordlists', Path(__file__).with_name('build-wordlists.py'))
bw = importlib.util.module_from_spec(spec)
spec.loader.exec_module(bw)

TOP_SUCCESSORS = 5
MIN_PAIR = 3
CLAUSE_END = set('.!?…')
# Every HOLDOUT_MODth line (0-based) is the eval slice of
# tools/eval-prediction.mjs (keep in sync). Training must never see it.
HOLDOUT_MOD = 100

DEMO_HEADS = {
    'en': ['how', 'what', 'thank', 'good', 'see', 'are'],
    'cs': ['jak', 'dobrý', 'děkuji', 'co'],
}


def count_pairs(dump_path, vocab):
    pairs = Counter()
    lines = 0
    opener = gzip.open if str(dump_path).endswith('.gz') else open
    f = opener(dump_path, 'rt', encoding='utf-8', errors='replace')
    try:
        for idx, line in enumerate(f):
            lines += 1
            if idx % HOLDOUT_MOD == 0:
                continue  # held out for the eval harness
            line = line.lower().replace('’', "'")
            if '{' in line:
                line = bw.ASS_TAGS.sub(' ', line)
            if "'" in line:
                line = bw.TAIL_JOIN.sub(r"'\1", line)
            prev = None
            for wt in line.split():
                if bw.JUNK.search(wt):
                    prev = None
                    continue
                tok = wt.strip(bw.EDGE_PUNCT)
                if tok not in vocab:
                    prev = None
                    continue
                if prev is not None:
                    pairs[(prev, tok)] += 1
                trail = wt[len(wt.rstrip(bw.EDGE_PUNCT)):]
                prev = None if any(c in CLAUSE_END for c in trail) else tok
    except EOFError:
        pass  # range-truncated gzip: keep everything read so far
    finally:
        f.close()
    return pairs, lines


def main():
    lang, dump_path, words_path, out_path = sys.argv[1:5]
    words = list(bw.read_old_words(words_path))  # frequency order
    vocab = set(words)
    pairs, lines = count_pairs(dump_path, vocab)

    by_head = {}
    for (h, w), c in pairs.items():
        if c >= MIN_PAIR:
            by_head.setdefault(h, []).append((-c, w))
    successors = {}
    for head in words:  # vocabulary frequency order
        ranked = sorted(by_head.get(head, []))  # count desc, ties alphabetic
        if ranked:
            successors[head] = [w for _, w in ranked[:TOP_SUCCESSORS]]

    header = (
        f"// Generated by tools/build-ngrams.py from the OPUS OpenSubtitles\n"
        f"// v2018 mono dump (attribution: https://www.opensubtitles.org).\n"
        f"// Top {TOP_SUCCESSORS} successors per {lang} vocabulary word, rank\n"
        f"// order, pair count >= {MIN_PAIR}. Words only, no counts: counts\n"
        f"// triple the size and add nothing for a five-chip strip.\n"
    )
    body = json.dumps(successors, ensure_ascii=False, separators=(',', ':'))
    Path(out_path).write_text(header + f"export const BIGRAMS = {body};\n",
                              encoding='utf-8')

    kept = sum(len(v) for v in successors.values())
    size = Path(out_path).stat().st_size
    print(f"{lang}: {lines} lines, {len(pairs)} distinct pairs; "
          f"{len(successors)} heads, {kept} successors; "
          f"{size // 1024} KB -> {out_path}")
    for head in DEMO_HEADS[lang]:
        print(f"  {head:7}: {', '.join(successors.get(head, ['-']))}")


if __name__ == '__main__':
    main()
