#!/usr/bin/env python3
"""Convert emojis/EmojiData.cs into emoji-data.js.

The .cs file comes from another project of the author's (a C# app) and
stays in the repo as the upstream source, the same way the word lists
keep their build script. Edit the .cs file, then re-run this script.

    python3 tools/convert-emoji.py

The file also holds an EmojiKeywords map (907 entries, ~40 kB). The
picker has no search field, so nothing would import that map; a lazy
module must not carry 40 kB of dead weight. Pass --keywords to emit it
as emoji-keywords.js when a search field lands.
"""

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "emojis" / "EmojiData.cs"

# Tab labels. The .cs keys are the ids; these are what the picker shows
# to a screen reader (the tab itself is the category's icon emoji).
LABELS = {
    "smileys": "Smileys",
    "gestures": "People",
    "animals": "Animals",
    "nature": "Nature",
    "food": "Food",
    "activities": "Activities",
    "travel": "Travel",
    "objects": "Objects",
    "symbols": "Symbols",
    "flags": "Flags",
}


def unescape(s):
    """Decode the C# string escapes that appear in the source.

    Most entries are literal emoji characters, but a few newer ones are
    written as \\U0001FACD escapes, which would otherwise reach the JS
    file as a backslash-U literal and render as text.
    """
    return re.sub(
        r"\\U([0-9A-Fa-f]{8})|\\u([0-9A-Fa-f]{4})",
        lambda m: chr(int(m.group(1) or m.group(2), 16)),
        s,
    )


def parse_categories(text):
    body = text[text.index("Categories = new()"):text.index("EmojiKeywords")]
    out = []
    for m in re.finditer(r'\["(\w+)"\] = \("(.*?)", new\[\]\s*\{(.*?)\}\)', body, re.S):
        cid, icon, items = m.group(1), unescape(m.group(2)), m.group(3)
        emojis = [unescape(e) for e in re.findall(r'"([^"]*)"', items)]
        out.append((cid, icon, emojis))
    return out


def parse_keywords(text):
    body = text[text.index("EmojiKeywords = new()"):]
    return [
        (unescape(m.group(1)), m.group(2))
        for m in re.finditer(r'\["([^"]*)"\] = "([^"]*)"', body)
    ]


def js_string(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def write_data(categories):
    lines = [
        "// Generated by tools/convert-emoji.py from emojis/EmojiData.cs.",
        "// Do not edit by hand: edit the .cs source and re-run the script.",
        "//",
        "// Each category is one tab of the emoji picker, in tab order.",
        "// `icon` is the emoji drawn on the tab itself.",
        "export const EMOJI_CATEGORIES = [",
    ]
    for cid, icon, emojis in categories:
        label = LABELS.get(cid, cid.capitalize())
        lines.append("  {")
        lines.append(f"    id: {js_string(cid)},")
        lines.append(f"    label: {js_string(label)},")
        lines.append(f"    icon: {js_string(icon)},")
        lines.append("    emojis: [")
        # Twelve per line: short enough to read in a diff, long enough
        # that the file stays about the size of the .cs source.
        for i in range(0, len(emojis), 12):
            row = ", ".join(js_string(e) for e in emojis[i:i + 12])
            lines.append(f"      {row},")
        lines.append("    ],")
        lines.append("  },")
    lines.append("];")
    lines.append("")
    (ROOT / "emoji-data.js").write_text("\n".join(lines), encoding="utf-8")


def write_keywords(keywords):
    lines = [
        "// Generated by tools/convert-emoji.py --keywords from",
        "// emojis/EmojiData.cs. Search terms for the emoji picker.",
        "export const EMOJI_KEYWORDS = {",
    ]
    for emoji, words in keywords:
        lines.append(f"  [{js_string(emoji)}]: {js_string(words)},")
    lines.append("};")
    lines.append("")
    (ROOT / "emoji-keywords.js").write_text("\n".join(lines), encoding="utf-8")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--keywords", action="store_true",
                    help="also write emoji-keywords.js (for a search field)")
    args = ap.parse_args()

    text = SOURCE.read_text(encoding="utf-8")
    categories = parse_categories(text)
    if not categories:
        sys.exit("no categories parsed: has the .cs format changed?")
    write_data(categories)
    total = sum(len(e) for _, _, e in categories)
    print(f"emoji-data.js: {len(categories)} categories, {total} emoji")
    for cid, _, emojis in categories:
        print(f"  {cid:12} {len(emojis):4}")

    if args.keywords:
        keywords = parse_keywords(text)
        write_keywords(keywords)
        print(f"emoji-keywords.js: {len(keywords)} entries")


main()
